### PR TITLE
Update version to 1.4.2

### LINKED ISSUE #67: Version information looks wrong
## Reproduction Rate
This happens every time.

## Steps to Reproduce
Run `tldr -v`

## Result
```
Xxxxs-MacBook-Pro:~ $ tldr -v
tldr v1.3.0 (v1.3.0)
Copyright (C) 2016 Arvid Gerstmann
Source available at https://github.com/tldr-pages/tldr-c-client
```

## Expected Result
```
Xxxxs-MacBook-Pro:~ $ tldr -v
tldr v1.4.1 (v1.4.1)
Copyright (C) 2016-2021 Arvid Gerstmann
Source available at https://github.com/tldr-pages/tldr-c-client
```
Although I am not sure why the version number is displayed twice, to be honest.

## Additional Information
I am using macOS Catalina (10.15.7) and Homebrew (3.3.3) to install, here's an example, showing 1.4.1 is downloaded but it displays 1.3.0:

```
Xxxxs-MacBook-Pro:~ $ brew install tldr
==> Downloading https://ghcr.io/v2/homebrew/core/tldr/manifests/1.4.1
Already downloaded: /Users/xxxxx/Library/Caches/Homebrew/downloads/7d2e739c6a1c2d56d0a50d3ef21d580d8248fd9e45ed004b29b473047d617d4c--tldr-1.4.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/tldr/blobs/sha256:6cfce860468cd9b2aa4a1db7d03cc989421666cdc2b55a041e1eb5f032fb2e80
Already downloaded: /Users/xxxxx/Library/Caches/Homebrew/downloads/166628835251bdf52acd52f3511292aa64930b2a8459d9e503f161255bda95e5--tldr--1.4.1.catalina.bottle.tar.gz
==> Pouring tldr--1.4.1.catalina.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/tldr/1.4.1: 10 files, 82.1KB
Xxxxs-MacBook-Pro:~ $ tldr -v
tldr v1.3.0 (v1.3.0)
Copyright (C) 2016 Arvid Gerstmann
Source available at https://github.com/tldr-pages/tldr-c-client
Xxxxs-MacBook-Pro:~ $ 
```

### PR DESCRIPTION
**Pull request by marchersimon**
Closes #67

### CODE REVIEW

**Comment by glawrence** [comment]
Looking at the makefile, is it trying to check it is being run from the local git clone and then use the tag as the version? This would explain why it is still 1.3.0 and also avoid the need to change the makefile for every build, just a thought

**Review by navarroaxel — APPROVED** [review]

**Comment by CleanMachine1** [comment]
Make sure to make another release.

**Review by CleanMachine1 — APPROVED** [review]

**Comment by CleanMachine1** [comment]
Merge when you feel correct!

**Comment by marchersimon** [comment]
I hope I didn't forget anything this time, but the [release workflow](https://github.com/tldr-pages/tldr-c-client/runs/4199170180?check_suite_focus=true) is failing. I already tried to re-run it.

**Comment by CleanMachine1** [comment]
```
refusing to allow a Personal Access Token to create or update workflow
```

the token doesn't have the correct privilege, @navarroaxel since your an admin, could you fix this?

**Comment by navarroaxel** [comment]
@CleanMachine1 where should I set the PAT?

**Comment by CleanMachine1** [comment]
I'm not too sure, however I assume it will be in [here](https://github.com/tldr-bot/homebrew-core) in the settings somewhere or unfortunately, possibly on the tldr-bot's account settings, which I assume we don't have access to

**Comment by CleanMachine1** [comment]
It might be called the BREW access token if its in this repo's secrets.

**Pull request merged**
