### PR TITLE
replace master with main

### PR DESCRIPTION
**Pull request by marchersimon**
As far as I know, the master to main change shouldn't affect any client, however it broke the C client. I always get `Error: Could Not Rename: /tmp/tldr70oDX4/tldr-master to /home/user/.tldrc/tldr-master/` and `/tmp/tldr70oDX4/` just doesn't exist.

However after changing everything to main it works again.

### CODE REVIEW

**Comment by bl-ue** [comment]
https://github.com/tldr-pages/tldr-c-client/pull/56#issuecomment-761781479

**Comment by marchersimon** [comment]
Ah, I see. But I think this should be done quickly since right now, the client is broken (at least for me). Also, I don't think it would be a big problem creating `tldr-main`, even if `tldr-master` exists. It is by far the easiest solution and it's merely an additional 36 MiB.

**Comment by owenvoke** [comment]
@marchersimon, I think maybe it should just be `tldr` instead of `tldr-main`, and we can do the cleanup/migration after?

**Comment by marchersimon** [comment]
Done

**Review by bl-ue — APPROVED** [review]

**Review by owenvoke — APPROVED** [review]

**Comment by CleanMachine1** [comment]
could we not mirror the branches

**Comment by marchersimon** [comment]
@owenvoke can we merge this?

**Comment by owenvoke** [comment]
This seems fine to me. However, I don't use the C client, so not entirely sure. 👍🏻

**Comment by marchersimon** [comment]
@sbrl @CleanMachine1 any thoughts?

**Comment by CleanMachine1** [comment]
Again, if we just mirror the branches we wont lose backwards support, so I'd recommend setting it up how we have our main repo

**Comment by marchersimon** [comment]
@CleanMachine1 I think you misunderstood this PR. It just changes from where the client downloads the files and how it names them. For me, the client is still broken and can't update without this change.

**Comment by CleanMachine1** [comment]
Then we should probably merge.

**Review by sbrl — APPROVED** [review]
Oops! This one must have slipped through my net.

Sure, we should merge this and make a new release ASAP.

**Pull request merged**
