### PR TITLE
Fix source url

### PR DESCRIPTION
**Pull request by bl-ue**
`tldr-pages/tldr-{cpp => c}-client`

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks for the PR @bl-ue! I can't merge this PR myself but I'll mention it in the [Gitter chat](https://gitter.im/tldr-pages/tldr) so hopefully a maintainer who can will do it.

**Review by owenvoke — APPROVED** [review]

**Review by sbrl — APPROVED** [review]
Oh, this one slipped through the net for me. Merging sincce it's trivial :-)

**Comment by sbrl** [comment]
Oh, the Travis build errored. Is that a problem?

**Comment by bl-ue** [comment]
@sbrl I don't think it is.  I didn't make any **real** source code changes.

**Pull request merged**
